### ISSUE TITLE
Errors encountered while running pwnapi modules

### ISSUE THREAD

**Issue by TarushS** [ndaprela/pwnapi#1]
Errors encountered while running pwnapi modules. Please refer the screenshot
![Screenshot from 2019-12-03 18-54-05](https://user-images.githubusercontent.com/38459708/70054835-4adb8b80-15fe-11ea-9cc9-d4f049160e87.png)

**Comment by ndaprela** [comment]
Could you try to do `make update` ? I replaced the problematic sequences with escape sequences, it should work now

**Comment by TarushS** [comment]
Well yeah that was the problem but still the when running checksec i get encountered with errors
![Screenshot from 2019-12-04 12-48-56](https://user-images.githubusercontent.com/38459708/70121455-9c365a00-1694-11ea-9f0f-c20ebb24dda8.png)

**Comment by ndaprela** [comment]
Which version of radare2 are you using?
Could you provide the output of this command: `r2 -v; r2 -c ij cmp`

**Comment by TarushS** [comment]
![Screenshot from 2019-12-05 21-48-07](https://user-images.githubusercontent.com/38459708/70253298-f3c5ea00-17a8-11ea-8dc1-1e5e760fda47.png)

**Comment by ndaprela** [comment]
That is old, current release is 4.1.0. That's why there's a missing key in the dictionary. Just update radare2 and you should be fine.
